-- ----------------------------------------------------
-- 1. Setup Support Tables (room_users, hardware_tokens, automation_rules)
-- ----------------------------------------------------

CREATE TABLE IF NOT EXISTS public.room_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    room TEXT NOT NULL DEFAULT 'Master Bedroom',
    pin_hash TEXT NOT NULL, -- SHA-256 hash of PIN
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, room)
);

CREATE TABLE IF NOT EXISTS public.hardware_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    token TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default ESP32 hardware token
INSERT INTO public.hardware_tokens (name, token)
VALUES ('esp32', 'esp32_secure_token_123456')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.automation_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    room TEXT NOT NULL DEFAULT 'Master Bedroom',
    trigger_device_id TEXT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    trigger_state BOOLEAN NOT NULL, -- true = Open/ON, false = Closed/OFF
    action_device_id TEXT NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
    action_state BOOLEAN NOT NULL,  -- true = ON, false = OFF
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ----------------------------------------------------
-- 2. ESP32 Hardware Authentication Helper Function
-- ----------------------------------------------------
CREATE OR REPLACE FUNCTION public.check_esp32_auth() 
RETURNS BOOLEAN AS $$
BEGIN
    RETURN (
        current_setting('request.headers', true)::json->>'x-esp32-auth-token' = 
        (SELECT token FROM public.hardware_tokens WHERE name = 'esp32' LIMIT 1)
    );
EXCEPTION WHEN OTHERS THEN
    RETURN FALSE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ----------------------------------------------------
-- 3. Enable RLS
-- ----------------------------------------------------
ALTER TABLE public.room_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hardware_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensor_log ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------
-- 4. Drop Existing Policies (Ensures Re-runnability)
-- ----------------------------------------------------
DROP POLICY IF EXISTS "Allow public read access" ON public.devices;
DROP POLICY IF EXISTS "Allow public read commands" ON public.commands;
DROP POLICY IF EXISTS "Allow public insert commands" ON public.commands;
DROP POLICY IF EXISTS "Allow public read sensor logs" ON public.sensor_log;
DROP POLICY IF EXISTS "Allow public insert sensor logs" ON public.sensor_log;

DROP POLICY IF EXISTS "Allow users to read their own room mappings" ON public.room_users;
DROP POLICY IF EXISTS "Allow read devices for authorized users and ESP32" ON public.devices;
DROP POLICY IF EXISTS "Allow update devices for authorized users and ESP32" ON public.devices;
DROP POLICY IF EXISTS "Allow read rules for authorized room users" ON public.automation_rules;
DROP POLICY IF EXISTS "Allow insert rules for authorized room users" ON public.automation_rules;
DROP POLICY IF EXISTS "Allow update rules for authorized room users" ON public.automation_rules;
DROP POLICY IF EXISTS "Allow delete rules for authorized room users" ON public.automation_rules;
DROP POLICY IF EXISTS "Allow read sensor logs for authorized room users" ON public.sensor_log;
DROP POLICY IF EXISTS "Allow ESP32 to insert climate logs" ON public.sensor_log;

-- ----------------------------------------------------
-- 5. Establish Strict Security Policies
-- ----------------------------------------------------

-- A. Policies for 'room_users'
CREATE POLICY "Allow users to read their own room mappings" 
ON public.room_users
FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

-- B. Policies for 'devices'
CREATE POLICY "Allow read devices for authorized users and ESP32" 
ON public.devices
FOR SELECT
USING (
    public.check_esp32_auth()
    OR EXISTS (
        SELECT 1 FROM public.room_users 
        WHERE room_users.room = devices.room 
        AND room_users.user_id = auth.uid()
    )
);

CREATE POLICY "Allow update devices for authorized users and ESP32" 
ON public.devices
FOR UPDATE
USING (
    public.check_esp32_auth()
    OR EXISTS (
        SELECT 1 FROM public.room_users 
        WHERE room_users.room = devices.room 
        AND room_users.user_id = auth.uid()
    )
)
WITH CHECK (
    public.check_esp32_auth()
    OR EXISTS (
        SELECT 1 FROM public.room_users 
        WHERE room_users.room = devices.room 
        AND room_users.user_id = auth.uid()
    )
);

-- C. Policies for 'automation_rules'
CREATE POLICY "Allow read rules for authorized room users" 
ON public.automation_rules
FOR SELECT 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.room_users 
        WHERE room_users.room = automation_rules.room 
        AND room_users.user_id = auth.uid()
    )
);

CREATE POLICY "Allow insert rules for authorized room users" 
ON public.automation_rules
FOR INSERT 
TO authenticated 
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.room_users 
        WHERE room_users.room = automation_rules.room 
        AND room_users.user_id = auth.uid()
    )
);

CREATE POLICY "Allow update rules for authorized room users" 
ON public.automation_rules
FOR UPDATE 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.room_users 
        WHERE room_users.room = automation_rules.room 
        AND room_users.user_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.room_users 
        WHERE room_users.room = automation_rules.room 
        AND room_users.user_id = auth.uid()
    )
);

CREATE POLICY "Allow delete rules for authorized room users" 
ON public.automation_rules
FOR DELETE 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.room_users 
        WHERE room_users.room = automation_rules.room 
        AND room_users.user_id = auth.uid()
    )
);

-- E. Policies for 'sensor_log' (climate metrics)
CREATE POLICY "Allow read sensor logs for authorized room users" 
ON public.sensor_log
FOR SELECT 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.devices d
        JOIN public.room_users ru ON d.room = ru.room
        WHERE d.id = sensor_log.device_id 
        AND ru.user_id = auth.uid()
    )
);

CREATE POLICY "Allow ESP32 to insert climate logs"
ON public.sensor_log
FOR INSERT
WITH CHECK (
    public.check_esp32_auth()
    OR auth.role() = 'authenticated'
);

-- ----------------------------------------------------
-- 6. Server-Side Automations Engine (Trigger & Function)
-- ----------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_device_automation()
RETURNS TRIGGER AS $$
DECLARE
    rule RECORD;
BEGIN
    -- Only run when status changes to avoid infinite recursion
    IF (OLD.status IS DISTINCT FROM NEW.status) THEN
        -- Loop through active rules triggered by this device
        FOR rule IN 
            SELECT action_device_id, action_state 
            FROM public.automation_rules 
            WHERE trigger_device_id = NEW.id 
              AND trigger_state = NEW.status 
              AND is_active = true
        LOOP
            -- Update the target device status
            UPDATE public.devices 
            SET status = rule.action_state,
                updated_at = timezone('utc'::text, now())
            WHERE id = rule.action_device_id;
        END LOOP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Attach Trigger to devices table
DROP TRIGGER IF EXISTS trg_device_automation ON public.devices;
CREATE TRIGGER trg_device_automation
AFTER UPDATE ON public.devices
FOR EACH ROW
EXECUTE FUNCTION public.handle_device_automation();

-- ----------------------------------------------------
-- 7. Seed Owner PIN (090207)
-- ----------------------------------------------------
INSERT INTO public.room_users (user_id, room, pin_hash)
SELECT id, 'Master Bedroom', '1db8bc6193142a33b0cc7ee9ba6ddcfa5eee733ada38713ac16d14b9ddcd4db9'
FROM auth.users
LIMIT 1
ON CONFLICT (user_id, room) 
DO UPDATE SET pin_hash = EXCLUDED.pin_hash;
