-- Create appliances/devices table
CREATE TABLE IF NOT EXISTS public.devices (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- 'light', 'ac', 'fan', 'lock'
    status BOOLEAN DEFAULT false NOT NULL,
    value INTEGER DEFAULT 0, -- e.g., brightness or temperature
    color TEXT DEFAULT '#ffffff', -- RGB color hex value
    room TEXT DEFAULT 'Bedroom',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert sample devices for your room including an RGB Light
INSERT INTO public.devices (id, name, category, status, value, color, room)
VALUES 
    ('esp32_relay_1', 'Main Ceiling Lights', 'light', true, 85, '#ffffff', 'Master Bedroom'),
    ('esp32_relay_2', 'Ambient Desk LED', 'light', false, 50, '#ffffff', 'Master Bedroom'),
    ('esp32_rgb_1', 'RGB Mood Lights', 'light', true, 100, '#ff007f', 'Master Bedroom'),
    ('esp32_relay_3', 'Air Conditioner', 'ac', true, 22, '#ffffff', 'Master Bedroom'),
    ('esp32_relay_4', 'Exhaust & Fan', 'fan', false, 3, '#ffffff', 'Master Bedroom'),
    ('esp32_door_sensor', 'Main Bedroom Door', 'lock', false, 0, '#ffffff', 'Master Bedroom')
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name, 
    category = EXCLUDED.category, 
    value = EXCLUDED.value, 
    color = EXCLUDED.color,
    room = EXCLUDED.room;

-- Enable Realtime Subscriptions for Next.js and ESP32
-- Note: If already enabled, this statement can be skipped
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.devices;

-- Enable Row Level Security (RLS)
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;

-- Allow read-only (SELECT) access for public users/anonymous clients
CREATE POLICY "Allow public read access" ON public.devices
    FOR SELECT TO anon USING (true);

-- Note: No INSERT, UPDATE, or DELETE policies are defined for public/anon roles.
-- Writes are restricted to server-side operations using the Supabase Service Role Key.


-- Create commands table for Alexa Speech commands
CREATE TABLE IF NOT EXISTS public.commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Realtime Subscriptions for commands table
-- Note: If publication doesn't exist, this statement might need project editor execution
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.commands;

-- Enable Row Level Security (RLS) on commands
ALTER TABLE public.commands ENABLE ROW LEVEL SECURITY;

-- Allow read-only (SELECT) access for public users/anonymous clients (for real-time dashboard listeners)
CREATE POLICY "Allow public read commands" ON public.commands
    FOR SELECT TO anon USING (true);

-- Allow insert (INSERT) access for public/anonymous clients (so Alexa/IFTTT webhooks can publish directly if needed)
CREATE POLICY "Allow public insert commands" ON public.commands
    FOR INSERT TO anon WITH CHECK (true);


-- Create sensor_log table for ESP32 climate readings
CREATE TABLE IF NOT EXISTS public.sensor_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL DEFAULT 'esp32_dht11',
    temp_c NUMERIC(5,2),
    humidity NUMERIC(5,2),
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Realtime Subscriptions for sensor_log table
-- Note: If publication doesn't exist, this statement might need project editor execution
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.sensor_log;

-- Enable Row Level Security (RLS) on sensor_log
ALTER TABLE public.sensor_log ENABLE ROW LEVEL SECURITY;

-- Allow read-only (SELECT) access for public users/anonymous clients
CREATE POLICY "Allow public read sensor logs" ON public.sensor_log
    FOR SELECT TO anon USING (true);

-- Allow insert (INSERT) access for public/anonymous clients (or server-side endpoint)
CREATE POLICY "Allow public insert sensor logs" ON public.sensor_log
    FOR INSERT TO anon WITH CHECK (true);


-- -----------------------------------------------
-- Create todos table for Alexa / dashboard tasks
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS public.todos (
    id TEXT PRIMARY KEY,                   -- UUID generated client-side
    title TEXT NOT NULL,
    completed BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Realtime Subscriptions for todos table
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.todos;

-- Enable Row Level Security (RLS) on todos
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- Allow anon clients to read todos (dashboard display)
CREATE POLICY "Allow public read todos" ON public.todos
    FOR SELECT TO anon USING (true);

-- Allow anon clients to insert todos (Alexa bridge inserts via dashboard webhook)
CREATE POLICY "Allow public insert todos" ON public.todos
    FOR INSERT TO anon WITH CHECK (true);

-- Allow anon clients to update todos (toggle completion from dashboard)
CREATE POLICY "Allow public update todos" ON public.todos
    FOR UPDATE TO anon USING (true) WITH CHECK (true);

-- Allow anon clients to delete todos (remove from dashboard)
CREATE POLICY "Allow public delete todos" ON public.todos
    FOR DELETE TO anon USING (true);
